# Generated by Django 5.0.3 on 2024-03-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
    ]
